Adding .cvsignore files and a few other things which probably should be included.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -14126,5 +14126,8 @@ if test "$no_create" != yes; then
 fi
 
 
-ln -s $ac_aux_dir/install-sh . 2>/dev/null
+if test ! -e install-sh
+then
+  ln -s "$ac_aux_dir/install-sh" . 2>/dev/null || echo "install-sh could not be linked."
+fi
 
